### ISSUE TITLE
SendBoxFnOnce -> BoxFnOnce

### ISSUE THREAD

**Issue by diwic** [stbuehler/rust-boxfnonce#3]
Hi,

Thanks for providing a stop-gap until Box<FnOnce> is stable.

Is there a way to convert a `SendBoxFnOnce` to a `BoxFnOnce`?

**Comment by stbuehler** [comment]
Sounds like a good idea, thanks - I just added it.

**Comment by stbuehler** [comment]
Also just released as [`0.1.1`](https://crates.io/crates/boxfnonce/0.1.1).

**Comment by diwic** [comment]
Thanks!
